### ISSUE TITLE
Fluid Grid Max Width

### ISSUE THREAD

**Issue by photodow** [IBM/carbon-elements#173]
As I was working to integrate `@carbon/grid` I realized we don't have a `max-width` on the `bx--fluid-grid`. Since we're expecting a `max-width` at the largest breakpoint (`1584px`/`99rem`), I talked to @joshblack & @jendowns to see what can be done.

I was about to just create a pull request in for this based on our conversation in `#carbon-elements` on Slack, but I wasn't crazy about my implementation in a couple areas (maybe I'm being picky), so I thought I'd open it up for discussion before I created it.

Without trying to avoid touching the current implementation too much I originally came up with three options.

#### Option 1
Add some sort of largest `max-width` modifier.

```css
.bx--fluid-grid--max { max-width: 99rem; }
```

While this works, I'm not crazy about it because it can technically modify any of the grids. It's not exactly specific to fluid. I thought about renaming to `.bx--grid--max`, but `.bx--grid` already has a `max-width`.

#### Option 2
Add `max-width` by default to `.bx--fluid-grid`.

```css
.bx--fluid-grid--max { max-width: 99rem; }
.bx--grid--fullwidth { max-width: 100%; }
```

Not that we can't go this route either, but it requires some sort of `full-width` modifier in case the desired outcome is full width.

#### Option 3
We could increase specificity a little, but it looks like [y'all try to avoid this](https://github.com/ibm/carbon-components/blob/master/.github/CONTRIBUTING.md#class-names).

```css
.bx--fluid-grid.bx--grid--max { max-width: 99rem; }
```

Let me know you're thoughts. I spent more time writing this than it would have taken to create a pull request. Ha :wink:

## Taking it a step further
I began to wonder if we got a little more involved touching existing pieces of the grid if we could make modifiers like this a little more clear. I don't know how open y'all are to this (I'm still a little unclear how far into the game I'm coming into all of this), but I figured I'd start the discussion.

Here is an example at a high level, using some off the cuff shorthand...

```css
.bx--grid { /* fluid by default */
    /* handle padding/margin at proper breakpoints */
}

.bx--grid--fixed { /* adaptive modifier */
    @media (min-width: 20rem) { max-width: 20rem; }
    @media (min-width: 42rem) { max-width: 42rem; }
    @media (min-width: 66rem) { max-width: 66rem; }
    @media (min-width: 82rem) { max-width: 82rem; }
    @media (min-width: 99rem) { max-width: 99rem; }
}

.bx--grid--fixed--extend { /* new modifier */
    @media (min-width: 99rem) { max-width: 100%; }
}

.bx--grid--max { max-width: 99rem; } /* new modifier */
.bx--grid--left { margin-left: 0; } /* new modifier */
.bx--grid--bleed { padding: 0; }
.bx--grid--condensed { padding: 1px; }
.bx--grid--padding { padding: 16px; }
/* I'm still trying to wrap my head around the use case for this one. haha */
.bx--grid--hang { padding-left: 0; }
```

I think I got everything, maybe minus aspect ratio? I chose to use fluid by default in `bx--grid` because that's just how the browser naturally renders a block element, so the modifiers from there just begin to build on top of that base. I'm sure we could flip those around if push came to shove. Anyway, hopefully, you get the idea I'm trying communicate. Let me know if you have any questions.

Do let me know your thoughts. If you'd even just prefer me to put a pull request for a short-term solution, and mull this other idea over or dismiss altogether. Just let me know!

**Comment by joshblack** [comment]
@jendowns how do you feel about this ^ I'm pretty neutral/open to a lot of this. Might be worth getting us all together too to make sure naming of the different grid permutations make sense, too!

**Comment by jendowns** [comment]
@photodow @joshblack Having a new `full-width` modifier that allows us to apply `@media (min-width: 99rem) { max-width: 100%; }` makes a lot of sense to me, that way people get the best of both words (i.e., they get their max width set at the high breakpoint... or they don't! depending on their needs).

**Comment by jendowns** [comment]
@joshblack 🤔  I kind of like the first option. (@SimonFinney what do you think?)

The second options isn't super clear to me -- what would the modifier for max-width do, if the fluid grid spans 100% by default?

**Comment by photodow** [comment]
I'm game for the `fullwidth` modifier approach. I think the majority of the pages on IBM.com will require a `max-width`, so I think intuitively it makes sense to set `max-width` as default from our point of view.

Something kind of like this?

```scss
/* minimal changes based on what's currently there */

.bx--grid {
    @media (min-width: 20rem) { max-width: 20rem; }
    @media (min-width: 42rem) { max-width: 42rem; }
    @media (min-width: 66rem) { max-width: 66rem; }
    @media (min-width: 82rem) { max-width: 82rem; }
    @media (min-width: 99rem) { max-width: 99rem; }
}

.bx--fluid-grid {
    max-width: 99rem;
}

.bx--grid--fullwidth { /* new modifier */
    @media (min-width: 99rem) { max-width: 100%; }
}
```

I'll throw this idea out one more time too with the `fullwidth` as we discussed above. :wink:
```scss
/* one grid, with different modifiers. I guess it depends on your perspective */

.bx--grid { /* fluid by default */
    /* handle padding/margin at proper breakpoints */
    @media (min-width: 99rem) { max-width: 99rem; }
}

.bx--grid--fixed { /* adaptive modifier */
    @media (min-width: 20rem) { max-width: 20rem; }
    @media (min-width: 42rem) { max-width: 42rem; }
    @media (min-width: 66rem) { max-width: 66rem; }
    @media (min-width: 82rem) { max-width: 82rem; }
}

.bx--grid--fullwidth { /* new modifier */
    @media (min-width: 99rem) { max-width: 100%; }
}
```
