### ISSUE TITLE
Automatic typography spacing

### ISSUE THREAD

**Issue by seejamescode** [IBM/carbon-elements#20]
**Is your feature request related to a problem? Please describe.**
Typography spacing is hard. Vertical spacing between two elements is usually based on which two typography elements are used. I don’t believe many devs will do proper measurements of that spacing when given a mock-up. And I doubt they will go to design documentation to find out what the spacing is supposed to be. It could be a lot more painless.

**Describe the solution you'd like**
Say I have the following HTML:
```html
<p class="type--heading-05">hello world</p>
<p class="type--body-02">this is the paragraph</p>
```

The source code from Carbon could be something like this:
```css
.type--heading-05 + .type--body-02 {
   margin-top: Xpx; // whatever the right pairing space is
}
```

**Describe alternatives you've considered**
This could also be opt-in, but I’m not sure if a design would ever have a need to break out of this. Here is how it would look as a opt-in class:
```html
<p class="type--heading-05">hello world</p>
<p class="type--body-02 type--spacing">this is the paragraph</p>
```

```css
.type--heading-05 + .type--body-02.type--spacing {
   margin-top: Xpx; // whatever the right pairing space is
}
```
