### ISSUE TITLE
Implement system for token values to output to JS and SCSS

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#221]
Currently, we are mirroring values between JavaScript and SCSS. Instead, we should have a source of truth that can output to either target. We have the following requirements for this system:

- Should be reasonably simple to edit for non-technical users
- Should be reasonably easy to reference values of other tokens without any strange syntax
- Can accurately export to JavaScript and SCSS, bonus points for pluggable architecture so we could target other systems as well

**Comment by joshblack** [comment]
One idea is to use [TOML](https://github.com/toml-lang/toml), some possible formats include:

## Colors

```toml
[swatch-name]
10 = "#ffffff"
20 = "#000000"
```

### Tokens (reference other colors)

```toml
token-name = "token-value"
# ...
interactive-01 = "blue-60" # or blue.60 ?
```

## Type

**Option 1**

```toml
[token-name]
font-size = 1 # step number
font-weight = 400
line-height = 0
  # Breakpoints
  [token-name.breakpoints.md]
    font-size = 2
  [token-name.breakpoints.lg]
    font-size = 3
  [token-name.breakpoints.max]
    font-size = 4
```

**Option 2**

```toml
[[tokens]]
name = "token-name-a"
font-size = 1
  [[tokens.breakpoints.md]]
    font-size = 2

[[tokens]]
name = "token-name-b"
```

### Icons

**Option 1**

```toml
[[icons]]
name = "icon-name"
friendly-name = "Icon Name"
description = """
Icon description
"""
sizes = [16, 20, 24, 32]
aliases = ["a", "b", "c"]
```

**Option 2**

```toml
[icon-name]
friendly-name = "Icon Name"
```
