### ISSUE TITLE
Decide on interop strategy with Carbon Components

### ISSUE THREAD

**Issue by joshblack** [IBM/carbon-elements#289]
Our goal over the next sprint is to integrate elements into carbon-components. As a result of this work, we're going to be documenting our public API for carbon-components alongside the changes that will happen as a result of this integration. However, we're running into a couple problems when introducing these packages into `carbon-components`.

The most notable problem is that mixins and functions in sass are determined by the last place they were defined. Initially, this makes sense for cases like:

```scss
@mixin a {
  width: 1px;
}

@mixin a {
  width: 2px;
}

.foo {
  @include a; // becomes width: 2px;
}
```

The initial thought was that, given we have identical names, we could create an alias to be called. However, this pattern will result in the same output:

```scss
@mixin a {
  width: 1px;
}

@mixin alias--a {
  @include a;
}

@mixin a {
  width: 2px;
}

.foo {
  @include alias--a; // becomes width: 2px;
}
```

In this case, even though the alias was defined earlier than the new `@mixin a`, it still uses the implementation for the last `@mixin a` defined.

It's also unfortunate that we cannot define mixins or functions in a conditional, or mixin/function, as that could have been another solution to this problem.

As a result, interop looks very challenging without renaming all mixins and functions to have a prefix. Would love to hear any thoughts/suggestions around how to proceed here!

---

#### Option 1: Rename carbon utilities and use as fallback

Before:

```scss
@mixin stable-name {
  // ...
}
```

After:

```scss
// Proposal
// stable-name -> stable-name-changed
@mixin stable-name-changed {
  // Default implementation
}

// Re-defined stable name
@mixin stable-name($arguments...) {
  @if feature-flag-enabled {
    // New implementation
  } @else {
    @include stable-name-changed($arguments...);
  }
}
```

- Pros
  - Able to keep feature flag system in place
- Cons
  - Updating code means chance to break
  - Might have to re-define mixins to accept parameter arguments instead of trusting global scope
  - Still requires prefix on elements side

#### Option 2: Start new branch for v10 in `carbon-components`

We could create a new branch for v10 that includes these breaking changes

- Pros
  - Easiest integration
- Cons
  - Will provide a worse migration path for consumers

#### Option 3: Figure out synonyms for elements exports

For example, instead of `$grid-breakpoints` we could do `$breakpoints`.
